env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends: 
  - 'eslint:recommended'
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: latest
rules:
  'no-unused-vars':
    - error
    -
      vars: all
      args: after-used
      ignoreRestSiblings: true
  'max-len':
    - error
    -
      code: 200
      tabWidth: 2
      ignoreUrls: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
  indent:
    - warn
    - 2
  semi:
    - error
    - always
  quotes:
    - error
    - single